version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - "3000:80" # Mapea el puerto del contenedor al host
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
